// Prepares the Roblox build for syncing into Studio.
// 1. Generates roblox/src/ReplicatedStorage/Shared/Config.luau from prototype/config.js (one source of truth).
// 2. Writes roblox/build/manifest.json listing every source file, Rojo-style:
//    *.server.luau -> Script, *.client.luau -> LocalScript, other *.luau -> ModuleScript, folders -> Folder.
// Usage: node tools/roblox_build.js   (then run tools/roblox_sync.luau in Studio, with the repo served on :8765)
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'roblox', 'src');
const C = require('../prototype/config.js');

const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const pad = n => '\t'.repeat(n);
function lua(v, d) {
  if (v === Infinity) return 'math.huge';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    if (!v.length) return '{}';
    return '{\n' + v.map(x => pad(d + 1) + lua(x, d + 1) + ',').join('\n') + '\n' + pad(d) + '}';
  }
  const keys = Object.keys(v);
  if (!keys.length) return '{}';
  return '{\n' + keys.map(k => pad(d + 1) + (IDENT.test(k) ? k : `[${JSON.stringify(k)}]`) + ' = ' + lua(v[k], d + 1) + ',').join('\n') + '\n' + pad(d) + '}';
}
const cfg = '-- GENERATED by tools/roblox_build.js from prototype/config.js. Do not edit by hand.\n' +
  '-- Arrays are 1-based here: pickaxe tier t is Config.pickaxes[t + 1], rarity index i is Config.rarities[i + 1].\n' +
  'return ' + lua(C, 0) + '\n';
fs.writeFileSync(path.join(SRC, 'ReplicatedStorage', 'Shared', 'Config.luau'), cfg);

const entries = [];
function walk(dir, parts) {
  for (const name of fs.readdirSync(dir).sort()) {
    if (name.startsWith('.')) continue;
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) {
      entries.push({ path: [...parts, name], className: 'Folder' });
      walk(full, [...parts, name]);
    } else if (name.endsWith('.luau')) {
      const base = name.replace(/\.(server|client)?\.?luau$/, '');
      const className = name.endsWith('.server.luau') ? 'Script' : name.endsWith('.client.luau') ? 'LocalScript' : 'ModuleScript';
      entries.push({ path: [...parts, base], className, url: '/' + path.relative(ROOT, full).split(path.sep).join('/') });
    }
  }
}
walk(SRC, []);
// Top-level folders are services (and StarterPlayer/StarterPlayerScripts), which already exist in Studio.
const manifest = entries.filter(e => !(e.className === 'Folder' && (e.path.length === 1 || e.path.join('/') === 'StarterPlayer/StarterPlayerScripts')));
fs.mkdirSync(path.join(ROOT, 'roblox', 'build'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'roblox', 'build', 'manifest.json'), JSON.stringify(manifest));
console.log(`Config.luau written, manifest has ${manifest.length} entries`);
